language: python
dist: bionic
sudo: true
python:
- '3.6'
- '3.7'
install:
- pip install tox-travis
script:
- tox
deploy:
  provider: pypi
  user: __token__
  skip_cleanup: true
  distributions: sdist bdist_wheel
  on:
    branch: master
    python: 3.7
  password:
    secure: M5/bOgvEYNv2hKIj872qjtrSVYJvYEOuu1VS6THqL5eqYpAnfh6+i00O8/L2/y+PJtqnIdidp30D8d4zZCwjKgPc9uSRq94sf8aOzvAy/dnZ8xu/YAZixc+pUkozFL6w1RZdJxVT4vTKZYbBXIBiAhl0P5Sab/2y0bhI/YtmM7elN/O19uz9ih9uQODBdER4RTi3/5uWX9SBRSssxossyjeOdn01jYIDGMHpxQeXygMOAcnlchT5nb8Mq2nS3Lk2h5g1cZSbFZ+qH3N5WWDPBTnTjIOz6FDzsxc813QjDSk6wNd275Vi3SVuIJ0QAcapwla77CknxuqRQ66ILC3iDyJ0DCihwZIouul2lMZE5EROx6EN2rma6si9fOkbjN5nxIdBf5CnDWs2F6iPiLmb9jDZ7NKykMWKDUeTYKo6KXrMO1OZUo9mYWFW+lEExM72eliiPviH+K6LukPO3BDc7wEuxtuKsg6usy+Re+7CpsXz7H3EWi9v/gmv8WGE6mUrSr1uDBlpwJrGHWSKynSfjBRo5I5koUINan0NmYxvyd6lqX36Y1aWQTnGvCwEUyThhkmCDaze5j9d1wMdnhuhhQz+s7QZhFD3/+vgU5hUkG90nqnHviSXxYtDmIqRMTht9b3OWEuUpJj9ZGyuMQOnboS6/5NXmnqPAjYHvxZXo2s=
