language: python
dist: bionic
sudo: true
python:
- '3.6'
- '3.7'
install:
- pip install tox-travis
script:
- tox
deploy:
  provider: pypi
  user: __token__
  skip_cleanup: true
  distributions: sdist bdist_wheel
  on:
    branch: master
    python: 3.7
  password:
    secure: xUTNxTU5BZ2XJbIA8SOX1d9lRC37DVC5dANVlrrk+z0l8Xp7L229lebZD0vogs+0AYYoJxi8WUQEfDKS/kjfOt1r9owQITwgQTgK2LKJwPnDb4kaq6EadSCY/EXIg0GM/5e3W2RoyV7R32TFea/i5m3o6Yu035Rbd+scvi/r5q0un+ws5+CYo+fYenFu46RoTJJShcltV76qI0/BLWBp2CkpOSjVMRNFmNyFqAc77JD0Rvz5Kd6ImhvTtQ1xhsNpl1w+/SqxnQWRN8MGaHURoSHZTUj6vMfOJiIk5Bdl/IC9xqodXhCjyDJh3o5RL9HzynqROS3VhTCpOgBkJcRkhvY66JAyjkMVVWJJsmGJLIGg2IFEza5LTLKMOWw1g6TL2AATUp4aD3lGjroJm5LSTcNxHtBIskOnaavdhCUDqUpTqloYmBe0p3fWU9B4GUODdyvfW4O5fPRFkuGduNTe04kZjpV11gfUfuiV/4COxzdgHq5+hhpRXTRRogHpwoJP7F05OQlSfrTYXUvV8F3YOQggeHv0e1oSxV2qc/Q6uFKz2wKTJ5blc0uBSA1HZjd2p7yHnI8eoj9TUyoUPlBz80906RaSTT3BpsN2zPs71VQtFUj8SAuv2w1ABzLJ4dOcaZnldvaS8rMGa4gyYYl/PexSMCmnZFBNpOe6Vj42tHM=
