language: python
dist: bionic
sudo: true
python:
- '3.6'
- '3.7'
install:
- pip install tox-travis
script:
- tox
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: JUFrJakgRIWnuH6xwV5WjtPzl348rhuLnHnqGURveIEeG0FYQfoftaPzslzfVpclwIKPu65ZnXnMFGrRtOeFQ6KM92GDzL++vG5/nxOFX8WnvVOwThV7yWFovQ1zGWuwKTXgbD80MA6jfRihriVE2Tl66IGqwq7oLCGQTqVBIFVpx7tiAsPSekBSDkGsn0PnHYPKYGblHKiifYsolxfkYAJoa6krFRlwi8MO9vUFNA0UwSWHwHsasc1C18WaFmBXOqEVed9x8VZwHA/DTqpWBrsDyRKVWNpZRvswc55YIdo4EwNKHKThNcUzhEavVvr4TXG8RuvCFDAoDrgL6qFsJLLamnnb7MEUYCQE/MuBCqfBMcD3qgwZK5Yrwgy6Duy9ZJgD6RHZ6GvrfYPMzPvV52sZIk/oF7OcKtIyueRPqu6KrqQ1mU/9GMqOZG2MJIetTBJNdOOazmZZVWGF3zK2fusWtvI7pJBSSq8xSCtQL5Ep/t1wormz977FZvoAO1rntErKuNlSkAkFbk5Uwoky2Y9e6knb6IHRVwSamndTYsp69uMZmGHLHRiom2SaIaOgGM2dtr9jPwH+rQMy/CEgA3SkIoljQAlKCHz8JT7/BaFogEg28VkotZ/1ToaZxtiHmp1HWKPBIamZQZT9/aqCKQN+mJfoDSSnqvXjihE6xtc=
  skip_cleanup: true
  distributions: sdist bdist_wheel
  on:
    branch: master
    python: 3.7
