language: python
dist: bionic
sudo: true
python:
- '3.6'
- '3.7'
install:
- pip install tox-travis
script:
- tox
deploy:
  provider: pypi
  server: https://upload.pypi.org/legacy/
  user: '__token__'
  skip_cleanup: true
  distributions: sdist bdist_wheel
  on:
    branch: master
    python: 3.7
